### PR TITLE
create page on hamburger menu

### PR DESCRIPTION
**Pull request by WardCunningham**
HTML forms can invoke an internal handler to create new pages. Here we add a hamburger menu page that has an HTML form that invokes this handler so that one can create pages without first making links.

image

### CODE REVIEW

**Comment by WardCunningham** [comment]
We can check to see if the new page name is in use here but it is too late to do something fancy like disable the create button. Perhaps we can redirect to the existing page rather than create the ghost future dialog?

https://github.com/fedwiki/wiki-plugin-html/blob/80b27749dd119aaa63463cc3f0c29f2aca51dc25/client/html.coffee#L11

**Comment by paul90** [comment]
I think showing the existing page, if one exists, would be the correct action.

**Comment by WardCunningham** [comment]
Current code just fabricates the ghost page. Better to just enter the link logic and do exactly what creating and clicking a link does. I don't know if this will be easy but it sure is easier to explain and defend.

**Comment by WardCunningham** [comment]
Ugh. The doInternalLink logic throws away the capitalization, needlessly it seems. I don't know that I'm up for digging this deep into core client javascript to fix this on a hypothetical risk.

https://github.com/fedwiki/wiki-client/blob/8e97a0565971c4e1b0642d86357b1ed7b007bd2c/lib/link.coffee#L10-L36

**Comment by WardCunningham** [comment]
I'm stalled on these suggested improvements. I consider the current risk small. Let's leave these safty suggestions to more ambitious times. Better to have this used rather than have the existing logic spread around haphazardly.

**Pull request merged**
