### PR TITLE
Include name and value of button among submitted params

### PR DESCRIPTION
**Pull request by dobbs**
David Bovill provided a collection of form test cases with various errors.
http://search.fedwiki.org/view/forms-in-wiki/view/forms-in-wiki_rev140

This PR is a **work in progress** to fix as many of them as we can.

### CODE REVIEW

**Comment by dobbs** [comment]
DON'T MERGE!  Turns out these fixes don't work in Safari.  Gonna have to be more tricky to get it working across browsers.

**Comment by WardCunningham** [comment]
Ha. That was looking easy.

**Comment by paul90** [comment]
Known issue - just needs transpiler adding into the build process - same as in either the video plugin or client. Hence the comment I made in chat last night. Latest version of coffeescript generates modern javascript, that's a bit too modern for Safari and Windows Edge and Internet Explorer.

**Comment by dobbs** [comment]
I'm still not seeing the button value in Safari.  This screenshot shows the results of having clicked the `HTML` button in Safari.  The URL echoed in the result shows an empty hash.
screen shot 2019-01-08 at 9 09 21 am

By contrast, this screenshot shows clicking `HTML` button in Firefox.  The URL echoed shows a url encoded json blob: `{"subject":"fav"}`
screen shot 2019-01-08 at 9 10 01 am

**Comment by dobbs** [comment]
This last commit correctly sends the button name and value on Safari, Chrome, and Firefox.

It's ready to be merged.

**Comment by paul90** [comment]
published in + wiki-plugin-html@0.3.3

**Pull request merged**
