### PR TITLE
Switch to javascript and switch to DOMPurify

### PR DESCRIPTION
**Pull request by dobbs**
My original interest in DOMPurify was for its support for SVG sanitization. I had bookmarked that with a view to creating an SVG plugin. But it occurred to me that this might work perfectly well inside the HTML plugin. Initial results are promising, but incomplete (more discussion below).

Also notable: 
The sanitize-caja repo hasn't been modified since 2017: https://github.com/mapbox/sanitize-caja
DOMPurify is getting active maintenance: https://github.com/cure53/DOMPurify

### CODE REVIEW

**Comment by dobbs** [comment]
I could use some help with this bug.

With the current html plugin on `master`, the SVG image doesn't display, but the create form generates a page with a correct title.
Screen Shot 2020-09-18 at 2 38 53 PM

With the code on this branch, the SVG image displays, but the create form does not work:
Screen Shot 2020-09-18 at 2 40 50 PM

**Comment by dobbs** [comment]
Next steps besides fixing this bug would be to find out how to scale the svg image instead of overflow.
And perhaps to also work on applying collaborative links to elements in SVG diagrams.

**Comment by dobbs** [comment]
Thank you for the help in today's hangout. The two main concerns are now resolved: <forms> are no longer broken by the sanitizer and we've figured out how to advise authors about SVG scaling questions.

**Comment by dobbs** [comment]
Added an SVG example and suggestions about `viewBox` and `width` attributes to the about page.

Screen Shot 2020-09-19 at 10 21 28 AM

**Comment by dobbs** [comment]
After over a year I think this PR is finally ready. In this most recent commit I've enabled authors to create internal links around arbitrary geometry by wrapping the SVG elements in an anchor tag with the title declared in a `data-title` attribute.

Last year at this time, this would have felt insufficient. But the past year of experiments with workflows using the frame plugin, we're now feeling confident that we can build translators to modify the svg from outside editors to make use of internal links where it makes sense to do so.

We have an example wiki running in glitch with this updated version of the HTML plugin for your review.
https://wiki-html-dompurify.glitch.me/view/welcome-visitors/view/html-plugin-examples/view/about-html-plugin
image

**Comment by paul90** [comment]
Published as + wiki-plugin-html@0.4.0 , and included in wiki@0.27.0

**Pull request merged**
